### ISSUE TITLE
decodeAudioData example does not work on Safari

### ISSUE THREAD

**Issue by bwl21** [mdn/webaudio-examples#5] opened 2018-01-13 10:47 UTC
-> https://mdn.github.io/webaudio-examples/decode-audio-data/

does not work on safari (Version 11.0.2 (11604.4.7.1.6) on OSX 10.11.6)

# Steps to reproduce

* open https://mdn.github.io/webaudio-examples/decode-audio-data/ on safari
* push "play" button
* nothing happens
* open debugger (ALT-CMD-I)
* you see the point of failure

```
  request.onload = function() {
    var audioData = request.response;

    audioCtx.decodeAudioData(audioData, function(buffer) {
        myBuffer = buffer;
        songLength = buffer.duration;
        source.buffer = myBuffer;
        source.playbackRate.value = playbackControl.value;
        source.connect(audioCtx.destination);
        //source.loop = true;

        loopstartControl.setAttribute('max', Math.floor(songLength));
        loopendControl.setAttribute('max', Math.floor(songLength));
      },

      function(e){"Error with decoding audio data" + e.err});   //<-- null is not an object

  }
```

In fact the error callback gets a `null` parameter.

**Comment by chrisdavidmills** [comment] 2018-01-18 21:32
Hrm. I tried changing the parameter to error, which is what it says it is in the spec. But it still doesn't work. This looks like a Safari bug to me - it works fine in other browsers.

**Comment by epistemex** [comment] 2018-01-19 04:30
I don't have Safari to test atm, but could you try setting `request.responseType = 'ArrayBuffer';` (i.e. case-sensitive variant)? Another alternative is to use `fetch()` instead of XMLHttpRequest.

**Comment by jakelewis3d** [comment] 2018-01-29 00:57
Also, the loop start and end times will not function as expected unless you un-remark the line:
source.loop = true;
which is currently remarked out.

**Comment by chrisdavidmills** [comment] 2018-01-29 09:17
@jakelewis3d this is a good point; I've fixed that.

**Comment by bwl21** [comment] 2018-01-29 09:20
@jakelewis3d does it work on safari with source.loop = true? if Yes, does it mean that percussion sounds cannot be used in safari?

**Comment by chrisdavidmills** [comment] 2018-07-05 10:49
Does someone fancy updating the example to offer an MP3 format file too? I will get to it eventually, but I'm crushingly busy right now.

**Comment by guest271314** [comment] 2019-12-15 16:13
@chrisdavidmills See attached `.zip` [viper.mp3.zip](https://github.com/mdn/webaudio-examples/files/3965129/viper.mp3.zip).

According to https://github.com/brion/ogv.js/issues/533 `decodeAudioData` does not work as expected at Safari.

**Comment by chrisdavidmills** [comment] 2019-12-16 08:18
@guest271314 thanks for the valient effort at fixing this, but ... it still doesn't seem to work for me. I also tried moving the audio context creation inside a user gesture, and rewriting the forking code that chooses between `AudioContext` and `webkitAudioContext`...

...Safari no longer errors. It now just fails silently 

¯\_(ツ)_/¯

**Comment by guest271314** [comment] 2019-12-16 14:46
@chrisdavidmills Do not currently have access to Safari, cannot verify the output. The closest that am able to test the code is Epiphany 3.28.5 where `.ogg` is decoded (https://github.com/brion/ogv.js/issues/533#issuecomment-565857607). Reading the code again,   `source.start(0)` should probably be within `decodeAudioData()` callback within `getData()`? 

Safari does fail or report missing coverage for several Web Audio API methods at https://wpt.fyi/interop/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html?label=master&label=experimental&aligned from https://github.com/web-platform-tests/wpt/blob/07d9f452d740d98ded5b11c176ba783fe9d80e5b/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.

**Comment by bwl21** [comment] 2020-01-06 09:56
I tried with the steps above. But it does not work either on Safari 13.9.4

**Comment by guest271314** [comment] 2020-01-06 16:55
Have you filed a Safari bug? Have you tried https://github.com/jfrancos/oggdec-wasm as workaround?

**Comment by thosch6** [comment] 2020-07-21 04:45
It's 2,5 years later as this problem was reported, and it still does not work on Safari! At least you should make note in the code that the example is not compatible with Safari!

**Comment by chrisdavidmills** [comment] 2020-07-21 08:05
> It's 2,5 years later as this problem was reported, and it still does not work on Safari! At least you should make a note in the code that the example is not compatible with Safari.

I've added a note to the page. I've tried to debug this a few times now, and never gotten anywhere, which is really frustrating. I just don't have the time to have a proper look at it.

**Comment by thosch6** [comment] 2020-07-21 10:33
I'd be so happy if it worked! I am running a guitar website with loops done in Flash which I have to replace urgently. So I tested the Web Audio Api example with http://wpt.live/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html in Safari on a Mac and it displays these two errors:

X Creating context for testing incorrectly threw ReferenceError: "Can't find variable: OfflineAudioContext".

X Fetching expected audio rejected incorrectly with TypeError: undefined is not an object (evaluating 'context.decodeAudioData'). Got Promise.

Are you aware of this?

**Comment by thosch6** [comment] 2020-07-21 18:40
So I have been researching a bit with the keywords "Web Audio Api Loop Demo" and found actually quite a few examples. Most of them do not work on Safari either, BUT there is this one where even 3 loops are going at the same time: https://forestmist.org/share/web-audio-api-demo 
Unfortunately, that code is too complex for me to understand, but you might find there the necessary inspiration to improve your solution which is the simple task of looping that most users like me need.
Maybe the problem lies in the way you load the audio file? When I click on 'viper.mp3' in Safari > Console > Resources, it says there was an error when loading the resource. 
Damm, where is the missing piece to make your nice and easy code work? I'd be glad to help you out where ever I could...

**Comment by thosch6** [comment] 2020-07-27 10:24
After playing around with the Web Audio API for a week, I noticed the following policy in Safari: It always wants a user gesture right before you start playback. You can not invoke downloading and playing an audio file at the same time from one button click! 
So if you change your code from:
play.onclick = function() {
	getData();
  	source.play(0);
to:
getData();
play.onclick = function() {
  	source.play(0);
Safari will start playback as intended. Unfortunately though, it will throw an error the next time you hit the play button again, as you are not allowed to call source.play(0) twice (check error in Chrome console).

**Comment by LukasAV** [comment] 2021-12-21 19:25
@thosch6 thanks for that hint. I am still dealing with this problem more than a year later. Did you find out more since then?
In a simple test I could confirm that getting the data using fetch in the same method as decodeAudioData does not work. But how far exactly do these steps have to be separated and what exactly is it about getting the data? Getting the cached file from an indexed DB did not seem to work either

**Comment by thosch6** [comment] 2021-12-22 07:43
I am using jake Archibald’s solution from 2016 for my loops, but there must be more up to date code by now on the web. See my player here: https://www.guitar.ch/en/guitars/jamtracks/jamtracks-modal-mixolydian.html

**Comment by LukasAV** [comment] 2022-01-06 16:00
Thanks for the tip.
In case this is helpful anyone else in the future: The solution for me was to actually do both the loading and decoding in one function but playing the sound in another function triggered by a separate event.

```js
let audioBuffer;
async function init() {
  const audioFile = await fetchSoundArrayBuffer();
  audioBuffer = await this.audioContext.decodeAudioData(audioFile);
}

function play() {
  const source = this.audioContext.createBufferSource();
  source.buffer = audioBuffer;
  source.connect(this.audioContext.destination);
  source.start();
}
```

**Comment by shreyas-jadhav** [comment] 2022-02-25 14:05
I had similar problem lately that `decodeAudioData` failing without much information. After trying lot of things realized,

the fix was actually using `.m4a` audio files for iOS safari browsers.

But keep in mind, Firefox and some other Non-Apple platforms won't work with `m4a`.

So we first do check to detect iOS safari browser and use `m4a` version else use the `mp3` everywhere.

**Comment by guest271314** [comment] 2022-02-25 14:08
@shreyas-jadhav Does iOS support MP3?

**Comment by shreyas-jadhav** [comment] 2022-02-25 14:12
according to my tests on our app, iOS 14 fails all the time to `decodeAudioData` with `.mp3`, while iOS 15 was failing 1/5 times roughly. i know this doesn't sound reasonable as a programmer. but it just worked for us when we switched to `.m4a`

**Comment by guest271314** [comment] 2022-02-25 14:26
Does iOS support `ScriptProcessorNode` or `AudioWorklet`? One option is to just create an application that converts any audio file to S16NE PCM.

**Comment by guest271314** [comment] 2022-02-26 06:51
Web Audio API specification https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata

> Audio file data can be in any of the formats supported by the [audio](https://html.spec.whatwg.org/multipage/media.html#audio) element.

Does Safari play MP3 files at HTML `<audio>` element?

**Comment by shreyas-jadhav** [comment] 2022-02-26 10:59
Yes it does support mp3 for `audio` element and even for `decodeAudioData`.

Actually there might be different reason why it wasn't working for us with mp3.
We had 6 mp3 files each of 10-20 MB. And the crashing happened because we decoded all the files simultaneously. (maybe because some memory issues idk) just now realized conversion to m4a has reduced the size of mp3 files and maybe thats why it isn't happening now. 
Seems that only iOS safari goes out of memory or something while decoding simultaneously.

sorry for posting unrelated & vague solution before.

**Comment by bsmth** [comment] 2022-11-02 14:46
Thanks all for the input here. It looks like this issue has been fixed by https://github.com/mdn/webaudio-examples/pull/32 which uses `.mp3` instead of `.ogg` so I am going to close this one as fixed.

Thank you :)

**Closed by bsmth** 2022-11-02 14:46 UTC
